#!/usr/bin/env python3
"""Pass 1 — render all 28 TABLE comments in living-models/chapters/*.md to populated
markdown tables. Most comments specify rows and columns inline; I render directly.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
CH = ROOT / "chapters"

TABLES = {}

# === Ch 01 ===
TABLES["P(Y|X) vs P(Y|do(X))"] = """| | $P(Y \\mid X)$ — observation | $P(Y \\mid do(X))$ — intervention |
|---|---|---|
| **Plain-language question** | What does $Y$ tend to look like *given that* we see $X$ in the data? | What would $Y$ become if we *set* $X$ to a value by acting on it? |
| **What kind of data supports it** | Historical observational records — transactions, logs, measurements as they occurred | Randomized experiments OR a causal model with explicit assumptions about mechanism |
| **J.C. Penney instantiation** | Customers who saw discount labels purchased more — visible in the historical receipt log | If we *removed* the discount labels, would those same customers still purchase more? — invisible in the historical log |
| **Can historical transaction data answer it?** | **Yes** — the data answers this directly | **No** — the answer is a different distribution that the data, by itself, does not contain |"""

TABLES["Silent failure modes"] = """| | Mechanical silent failure | Epistemic silent failure |
|---|---|---|
| **What fails** | A pipeline component breaks, returns stale or partial data, but reports success | The framework cannot distinguish observation from intervention; the wrong question is being asked |
| **Why no error signal appears** | The component's success criterion is technical ("HTTP 200, row count > 0") and is met | There is no error signal because the math is correct; the conceptual frame is not |
| **Example from the chapter** | The WAU dashboard pipeline that lost a join condition and silently dropped half the user base | J.C. Penney inferring from association that customers preferred discounts when the association was generated by the framing itself |
| **Detection method** | Independent reconciliation against a second source of truth; canary queries with known answers | Pearl's Ladder classification — explicit check that the question and the answer live on the same rung |
| **Recovery difficulty** | Mechanical, often hours: fix the join, replay the pipeline | Epistemic, often months: rebuild the analytical apparatus around interventional reasoning |"""

TABLES["Four analytical system types compared"] = """| System type | Causal structure | Counterfactual reasoning | Continuous updating | Treatment orientation |
|---|---|---|---|---|
| **Dashboard** | No — encodes correlations, not mechanisms | No — describes what occurred, not what would have | Partial — refreshes data, not structure | No — surfaces metrics, not interventions |
| **Predictive model** | No — fits associations in observational data | No — predicts on the same distribution it was trained on | Partial — periodic retraining; structure stays fixed | No — outputs forecasts, not ranked actions |
| **Prescriptive system** | Partial — uses optimization atop a predictive layer | No — recommends actions but cannot answer "what would have happened if" | Partial — depends on the underlying predictive layer | Yes — output is a recommended action |
| **Living Model** | **Yes** — DAG plus structural equations encode mechanism | **Yes** — abduction-action-prediction on the SCM | **Yes** — Bayesian parameter updating + structural drift detection | **Yes** — output is an EV-ranked intervention list |"""

# === Ch 03 ===
TABLES["Three-column table contrasting batch-reporting posture"] = """| Dimension | Batch-reporting posture | Continually-updated posture |
|---|---|---|
| **Information standard before acting** | Wait for the next report cycle; act on what was true at last refresh | Act on the freshest reading the latency budget allows; the question is whether *this* number is good enough for *this* decision |
| **Tolerance for being wrong** | Low at the level of the report; the report is taken as authoritative | High at any single reading; the loop is what produces correctness over time |
| **Relationship to uncertainty** | Hides uncertainty inside the cycle gap; the report shows a number without an interval | Carries uncertainty as a first-class output — every reading has a confidence band |
| **How confidence is expressed** | A single decimal place, no interval | An interval and a freshness timestamp on every figure |
| **What "waiting" costs** | Nothing visible — the cycle is the heartbeat | A specific opportunity cost named in the latency budget |"""

TABLES["Audit summary for the retail forecasting system"] = """| Latency | Measured value | Acceptable threshold for a weekly ordering decision | **Binding constraint?** | Layer responsible |
|---|---|---|---|---|
| **Data latency** | ~2 hours from POS event to warehouse | < 24 hours | No | Technical |
| **Model latency** | Re-scored every 6 hours | Within the cycle | No | Technical |
| **Decision latency** | **5 days from updated forecast to acted-on order** (waits for Tuesday review) | < 24 hours | **Yes** | **Organizational** |

*The binding constraint is decision latency, not data or model latency. The technical pipeline is faster than the organizational cadence that consumes it.*"""

TABLES['"real-time" claim vs. "continually updated" claim'] = """| Practitioner question | "Real-time" answer | "Continually updated" answer |
|---|---|---|
| **What is the data latency?** | "It's real-time." (terminates the conversation) | "Two hours from event to dataset, with a freshness timestamp on every reading." |
| **What is the model latency?** | "It's real-time." | "Re-scored every six hours; the staleness alarm fires at twelve." |
| **What is the decision latency?** | "It's real-time." | "Five days from updated output to acted-on decision, gated by the Tuesday review." |
| **Is this adequate for my decision?** | "It's real-time." | "Adequate for a weekly ordering decision; inadequate for a same-day routing decision." |
| **What would make it better?** | "It's real-time." | "Move the Tuesday review to a daily standing item; data and model latency are not the bottleneck." |

*"Real-time" forecloses every question. "Continually updated" answers each one specifically.*"""

# === Ch 04 ===
TABLES["Three-row reference table"] = """| Property of the risk | Visible in the collapsed score? | Visible in distributional analysis? |
|---|---|---|
| **Distributional shape** | **No** — the score reduces shape to a single number; bimodal, fat-tailed, and unimodal risks read identical | **Yes** — the histogram, density, or full distribution preserves shape directly. *Example: a bimodal supply-chain risk that scores 9 looks identical to a unimodal one until you plot it.* |
| **Recoverability** | **No** — the score does not distinguish a $1M loss that compounds into ruin from one that is absorbed in a quarter | **Yes** — the analysis carries the conditional path forward. *Example: a 5% probability of $20M loss is survivable for a $1B firm, fatal for a $50M firm — the score cannot tell them apart.* |
| **Typical vs. tail behavior** | **No** — the score averages tail and median into the same cell; a low-probability catastrophic outcome is hidden inside the same number as a high-probability moderate outcome | **Yes** — VaR, CVaR, and the full distribution surface tail behavior explicitly. *Example: a heat-map score of "high" can mean a 50% chance of a $1M loss or a 1% chance of a $50M loss — operationally different decisions.* |"""

TABLES["Sample risk register"] = """| Rank | Risk | Probability (1–5) | Impact (1–5) | Score | The decision the score gets wrong |
|---|---|---|---|---|---|
| 1 | **Routine system downtime** | 3 | 3 | **9** | Treated as top priority despite being recoverable in hours |
| 2 (tie) | **Vendor contract dispute** | 4 | 2 | 8 | Likely, modest cost — operational handling |
| 2 (tie) | **Regulatory audit failure** | 2 | 4 | 8 | Rare but reputation-altering — requires a different response than a vendor dispute |
| 4 (tie) | **Billing errors** | 5 | 1 | 5 | Frequent annoyance — distributed handling, low priority |
| 4 (tie) | **Critical infrastructure breach** | 1 | 5 | 5 | Catastrophic and possibly existential — sorted equal to billing errors |

*Sorted by score, the register treats billing errors and an infrastructure breach as equal priority. The two pairs at scores 8 and 5 each contain risks whose appropriate responses are categorically different. The collapse to one number actively misleads the prioritization the register exists to support.*"""

# === Ch 06 ===
TABLES["Regression equation vs. structural causal model"] = """| Property | Regression Equation | DAG | SCM |
|---|---|---|---|
| **Distinguishes cause from effect** | No — symmetric in $X$ and $Y$ | **Yes** — arrows are asymmetric | **Yes** — structural equations are asymmetric |
| **Handles direct vs. indirect effects** | Partial — coefficients confound direct + indirect | **Yes** — paths are decomposable | **Yes** — direct, indirect, and total effects all computable |
| **Supports the do-operator** | No | Partial — the graph supports the calculus, but parameters live elsewhere | **Yes** — full parametric counterfactual computation |
| **Supports counterfactuals** | No | No — the graph alone is not enough for Rung 3 | **Yes** — abduction-action-prediction runs on the SCM |
| **Makes assumptions visible** | No — assumptions hide in functional form | **Yes** — every absent arrow is a falsifiable assumption | **Yes** — equations + absent arrows + noise structure |
| **Scope** | Single-outcome, fitted to data | Global — represents the joint mechanism for all variables | Global — augmented with parametric mechanism |"""

# === Ch 08 ===
TABLES["Common regression errors classified by causal role"] = """| Error | Variable's causal role | What the analyst usually believes they are doing | Direction of resulting bias | What the backdoor criterion says instead |
|---|---|---|---|---|
| **Controlling for a mediator** | $M$ lies on the causal path $X \\to M \\to Y$ | "I'm controlling for everything that varies with $X$" — assumed to make the estimate cleaner | Toward zero — the indirect effect is partialled out | Mediators must *not* be conditioned on when estimating the total effect; condition on them only when isolating direct effects |
| **Omitting a confounder** | $Z$ is a common cause of $X$ and $Y$ | "I'm running the simplest model that fits" | Direction depends on the sign of the confounding; magnitude can dwarf the true effect | The backdoor criterion identifies a sufficient $Z$; estimate is identifiable only if all backdoor paths are blocked |
| **Controlling for a collider** | $C$ is caused by both $X$ and $Y$ (or their descendants) | "I'm adjusting for as much as possible" — adding more controls assumed to be safer | Opens a backdoor path that was previously closed; *introduces* spurious association | Colliders must *not* be conditioned on; doing so makes the estimate worse, not better |"""

# === Ch 09 ===
TABLES["Worked counterfactual"] = """| Step | Operation | Equation | Result |
|---|---|---|---|
| **1. Abduction** | Recover the case-specific noise terms by plugging the observed values into the SCM | $L_\\text{obs} = \\beta_M M + U_L \\Rightarrow U_L = L_\\text{obs} - \\beta_M M$ ; same for $U_R$ | $U_L = 10$, $U_R = -50$ |
| **2. Action** | Modify the SCM by replacing the structural equation for $M$ with a fixed assignment | Replace $M = f_M(\\cdot)$ with $M := 200$ | New SCM with $M$ fixed at the counterfactual value |
| **3. Prediction** | Run the modified SCM forward, holding the recovered noise terms fixed | $L_\\text{cf} = \\beta_M \\cdot 200 + U_L$ ; $R_\\text{cf} = \\gamma_M \\cdot 200 + U_R$ | $L_\\text{cf} = 90$, $R_\\text{cf} = 400$ |
| *Average-case prediction (no abduction, for contrast)* | *Run the modified SCM with population-average noise* | $L = \\beta_M \\cdot 200 + E[U_L]$ | *$L = 80$ — misses the case-specific signal* |"""

TABLES["Pre-factual vs. retrospective counterfactuals"] = """| | Pre-factual counterfactual | Retrospective counterfactual |
|---|---|---|
| **When evaluated** | Before the action is taken; a forward question | After the action and outcome have both occurred |
| **What is conditioned on** | Pre-action characteristics of the case | Both the pre-action characteristics *and* the observed outcome |
| **What abduction recovers** | Distributional noise consistent with the pre-action evidence | Noise sharpened by the observed outcome — case-specific information that the pre-action data did not contain |
| **Precision of noise recovery** | Lower — many noise vectors are consistent with the pre-action data | Higher — the observed outcome eliminates the noise vectors that would have produced different outcomes |
| **Primary use case** | Decision support: *what should I do?* | Audit / accountability: *what would have happened if we had done differently?* |
| **Example from the chapter** | Before prescribing the drug: *what would $L$ and $R$ be at $M = 200$?* | After the recovery: *given the observed $L, R$ at $M = 100$, what would they have been at $M = 200$?* |"""

TABLES["Necessary vs. sufficient causation"] = """| | Necessary cause | Sufficient cause |
|---|---|---|
| **Formal definition** | The outcome would not have occurred without the cause | The cause would have produced the outcome on its own |
| **Counterfactual query** | $P(Y_{X=0} = 0 \\mid X = 1, Y = 1)$ — would the outcome *not* have occurred if the cause hadn't? | $P(Y_{X=1} = 1 \\mid X = 0, Y = 0)$ — would the cause have produced the outcome if it had been applied? |
| **Probability measure** | **PN** (Probability of Necessity) | **PS** (Probability of Sufficiency) |
| **Legal / ethical standard it supports** | The but-for test in tort law; attribution of responsibility | Predictive reliability of the causal mechanism; warranty claims |
| **Example from the chapter** | The drug recovery — would the patient have recovered without the drug? | The warehouse fire — would the smoldering rag have caused the fire on its own? |
| **What a high value implies** | The cause was load-bearing — without it, the outcome would not have occurred | The cause is reliable — when it occurs, the outcome follows |
| **What a low value implies** | The outcome would have occurred anyway — the cause was not load-bearing | The cause is unreliable — sometimes the outcome does not follow |"""

# === Ch 11 ===
TABLES["Two-column reference table for SUTVA"] = """| | Component 1 — No interference | Component 2 — No hidden variations |
|---|---|---|
| **Formal statement (plain language)** | One unit's treatment status does not affect another unit's outcome | The treatment is the same thing everywhere it is applied |
| **What it requires in practice** | The units are independent of each other in the relevant causal pathways | The mechanism, dosage, and conditions are standardized across the trial |
| **Canonical failure mode** | Spillover — the treatment effect leaks through social, market, or network ties | Heterogeneous implementation — the same nominal treatment is delivered differently in different places |
| **Direction of bias when violated** | Toward zero (control benefits from spillover, attenuating the difference) | Unpredictable — depends on whether high- or low-quality implementations dominate the trial |"""

TABLES["JTPA study SUTVA audit"] = """| Violation in JTPA | Component | Mechanism | Effect on the estimate | Design / analytic remedy |
|---|---|---|---|---|
| **Cross-site variation in services** | Component 2 — hidden variations | Different sites delivered different training types under the same JTPA banner | Attenuates the average; masks heterogeneity across site types | Stratify or cluster-randomize at the site level; report site-conditional effects |
| **Imperfect compliance** | Component 2 — hidden variations | Some treated individuals received no training | ITT < TOT — both estimands are valid, but they answer different questions | Report ITT *and* TOT; encouragement design if compliance is itself the lever |
| **Local labor market wage spillover** | Component 1 — interference | Program graduates compete with each other in local labor markets, depressing local wages | Underestimates individual skill gain; overestimates market-level wage impact | Cluster-randomize at the labor-market level; supplement with general-equilibrium analysis |"""

TABLES["Design selection guide"] = """| Design alternative | SUTVA violation addressed | Key diagnostic question to determine applicability | What the design estimates | Primary limitation |
|---|---|---|---|---|
| **Cluster-randomized trial** | Component 1 — interference | "Within what unit boundary do treated and control units interact?" | Cluster-level average treatment effect | Lower power per unit; requires many clusters |
| **Time-staggered rollout** | Component 1 — interference | "Can we sequence the rollout so adjacent cohorts don't overlap?" | Difference-in-differences across phased cohorts | Confounded with time trends; requires modeling time effects |
| **Encouragement design** | Component 2 — hidden variations (compliance) | "Can we randomly *encourage* treatment without forcing it?" | Local average treatment effect (LATE) on compliers | Only the complier subgroup is identified; external validity caveat |
| *When multiple violations are present* | — | Address the most consequential by design; handle residual violations analytically | — | — |"""

# === Ch 12 ===
TABLES["Five plumbing factors"] = """| Plumbing factor | Definition | Classic example | Why causal models miss it | Plumbing-fix category |
|---|---|---|---|---|
| **Administrative friction** | Procedural steps (forms, approvals, manual entry) that reduce take-up out of proportion to monetary cost | Tangier study: removing forms increased take-up sevenfold without changing economic terms | The model parameterizes the *intervention*, not the *steps* that gate it | Process redesign — remove steps |
| **Default architectures** | The choice that operates absent active opt-in | Save More Tomorrow (default-on retirement saving) | Defaults are upstream of the variables most models include | Set the default to the action you want |
| **Incentive architectures** | The schedule under which actors receive rewards or sanctions | Sales-team commissions that distort intervention behavior | The model treats incentives as constants, not as instruments | Align the incentive with the intended behavior |
| **Behavioral biases** | Systematic deviations from the rational agent assumed by the causal model | Loss aversion, hyperbolic discounting | The model assumes the response is the rational best-response | Frame the intervention to the bias rather than against it |
| **Institutional inertia** | The resistance of the organization to changing its routines | A pricing change blocked by a six-month legal review cycle | The model has no representation of the organization's clock | Sequence the intervention to the institution's actual cadence |"""

TABLES["Three Living Model demands"] = """| Demand | What it requires | What breaks without it | Part Three chapter |
|---|---|---|---|
| **Deployment Instrumentation** | Logging at the point of action — what was recommended, what was done, what happened | The plumber's gap is invisible; the model cannot self-correct | Ch 19 (Causal Brain Executive Report) and Ch 20 (DecisionOps) |
| **Continual Structural Updating** | Drift detection on edges, not just parameters; re-elicitation triggers | The graph drifts past its valid window without anyone noticing | Ch 17 (Resolving the Graph) and Ch 20 (Keeping the Model Alive) |
| **Human-in-the-Loop Orchestration** | Named accountability at each stage; the model recommends, the human decides | The recommendation gets executed without the judgment that licenses it | Ch 19 (Executive Report named-owner block) |"""

# === Ch 14 ===
TABLES["worked example of variable identification"] = """| Expert's initial variable | Clarification question(s) applied | Outcome |
|---|---|---|
| Competitive position | "What does *competitive position* mean precisely? Market share, price premium, or something else?" | **Refined and included** as `relative_price_premium` |
| Brand strength | "Brand awareness, brand preference, or brand loyalty? Which one drives the decision you're modeling?" | **Refined and included** as `brand_preference_index` |
| Organizational capability | "Capability to do what, specifically? Engineering throughput? Sales conversion? Operations cost control?" | **Excluded** — too broad, no agreed measurement; replaced by three specific capability variables introduced later |
| Customer trust | "Trust as measured by NPS, by repeat-purchase rate, or by some other instrument?" | **Merged** with `customer_satisfaction_score` |
| Customer satisfaction | (covered above) | **Refined and included** as `customer_satisfaction_score` |
| Market opportunity | "What's the unit — addressable market size in dollars, in segment count, in growth rate?" | **Refined and included** as `addressable_market_dollars` |
| Channel strength | "Direct sales, partner channel, or both? Which one is the variable that matters?" | **Refined and included** as `partner_channel_coverage` |
| Pricing power | "Price elasticity? Margin? Floor price?" | **Merged** with `relative_price_premium` |
| Product fit | "Fit to whose needs? The buyer's, the user's, the regulator's?" | **Refined and included** as `buyer_jtbd_fit` |
| Operational readiness | "Ready to do what specifically? Ship in volume? Support 24×7? Localize?" | **Refined and included** as `support_sla_capacity` |
| Risk profile | "Financial risk, regulatory risk, or operational risk?" | **Excluded** — three different things; will appear as three separate downstream variables if needed |
| Speed to market | "Time from decision to first revenue? Or to general availability?" | **Refined and included** as `time_to_first_revenue_weeks` |
| **Result** | 12 → 8 variables | — |

*Variable identification is the most underestimated phase. Every hour spent here saves three hours of structural confusion later.*"""

TABLES["full CPT versus Noisy-OR parameterization"] = """**Full CPT — 16 parameters required (one per row)**

| $P_1$ | $P_2$ | $P_3$ | $P_4$ | $P(Y = 1 \\mid \\text{parents})$ |
|:---:|:---:|:---:|:---:|---|
| 0 | 0 | 0 | 0 | $p_{0000}$ |
| 0 | 0 | 0 | 1 | $p_{0001}$ |
| 0 | 0 | 1 | 0 | $p_{0010}$ |
| 0 | 0 | 1 | 1 | $p_{0011}$ |
| 0 | 1 | 0 | 0 | $p_{0100}$ |
| 0 | 1 | 0 | 1 | $p_{0101}$ |
| 0 | 1 | 1 | 0 | $p_{0110}$ |
| 0 | 1 | 1 | 1 | $p_{0111}$ |
| 1 | 0 | 0 | 0 | $p_{1000}$ |
| 1 | 0 | 0 | 1 | $p_{1001}$ |
| 1 | 0 | 1 | 0 | $p_{1010}$ |
| 1 | 0 | 1 | 1 | $p_{1011}$ |
| 1 | 1 | 0 | 0 | $p_{1100}$ |
| 1 | 1 | 0 | 1 | $p_{1101}$ |
| 1 | 1 | 1 | 0 | $p_{1110}$ |
| 1 | 1 | 1 | 1 | $p_{1111}$ |

**Noisy-OR — 5 parameters required**

| Parameter | Meaning |
|---|---|
| $q_0$ | Background probability of $Y=1$ when no parent is active |
| $q_1$ | Inhibition probability for $P_1$ — probability $P_1$ fails to activate $Y$ when $P_1=1$ |
| $q_2$ | Inhibition probability for $P_2$ |
| $q_3$ | Inhibition probability for $P_3$ |
| $q_4$ | Inhibition probability for $P_4$ |

- *When parental independence holds:* Noisy-OR is dramatically more efficient — 5 elicitations instead of 16.
- *When parental independence fails:* the model is wrong in a specific, diagnosable way — interactions between parents are invisible. The price of the structural assumption is paid in the residuals."""

TABLES["Six-barrier diagnostic reference table"] = """| Barrier | Why it is structural | Binding context | Architectural response |
|---|---|---|---|
| **1. Engagement duration** — KEBN takes weeks to months per session | The bottleneck is human attention, not algorithmic speed; better algorithms don't compress an expert's time budget | Fast-moving corporate decisions where leadership cannot commit eight weeks | Ch 16 — LLM-guided 45-minute first-pass interview |
| **2. Methodological skepticism** — corporate experts trust intuition over structured probabilistic protocols | A discipline gap, not a tooling gap; better software does not bridge it | Senior leadership accustomed to qualitative judgment over formal models | Structured scaffolding that encodes facilitator protocols inside the tool, not the user |
| **3. Output legibility** — KEBN outputs are static documents, not living artifacts | The decision-maker needs an artifact that updates, not a snapshot | Organizations whose decisions recur and whose models therefore must persist | Ch 19 — Living Model output format with audit record + versioning |
| **4. Visualization barrier** — DAGs in current tooling are slow, ugly, and intimidating to non-technical viewers | The viewer's experience determines adoption; the math doesn't care | Boardroom and executive audiences with no graph-theory background | Speed and visual legibility built into the rendering layer |
| **5. Single-use modeling** — each engagement produces a one-off model that is not reused | Without a governance model, knowledge accumulated in one session does not transfer | Organizations with related decisions across business units | Governed reusable model artifact with version control and re-elicitation triggers |
| **6. Static parameterization** — once parameters are set, they don't update with new evidence | Bayesian updating is mathematically simple but operationally absent from KEBN tooling | Any deployment where the world changes between elicitations | Ch 20 — Continuous Bayesian methods on edge parameters; structural drift detector |

*Each barrier is real. None is insuperable. The architecture of Chapters 15–17 is designed to address all six simultaneously — addressing any subset leaves the others blocking adoption.*"""

# === Ch 15 ===
TABLES["Domain-matching audit framework"] = """| Source domain | Target domain | Assumptions that hold in source but not target | Canonical failure | Elicitation probe to surface the mismatch |
|---|---|---|---|---|
| **Physics** | Finance | Time-invariant laws; stationary distributions; no reflexivity between observer and observed | "Physics envy" — Black–Scholes assumed lognormal returns; the 2008 crash showed the distribution wasn't stationary | "What about this domain would invalidate a closed-form physical-style model?" |
| **Engineering** | Medicine | Components have specifications; failure modes are characterizable; tests are non-destructive | A device-reliability mindset applied to drug efficacy ignores patient heterogeneity and adherence | "If we treated this patient as a *component*, what would we be missing?" |
| **Economics** | Ecology | Agents optimize; preferences are stable; equilibrium exists | Cap-and-trade designs assume substitutability that ecosystem services don't actually have | "What about this system makes substitution between units of [outcome] not equivalent?" |
| **Military** | Business strategy | Adversary is rational; objectives are clear; engagement is bounded in time | "Crush the competition" rhetoric masks that customers, regulators, and partners are not adversaries | "Who in this picture isn't trying to win — and what does that change?" |"""

TABLES["Kind vs. wicked environments"] = """| Domain | Environment type | Feedback characteristics | Reliability of expert intuition | Elicitation posture |
|---|---|---|---|---|
| **Diagnostic clinical reasoning** | Kind | Fast, accurate, repeatable feedback per case | High — pattern-matching after thousands of cases is reliable | Lean on intuition; probe for the specific feature triggering the diagnosis |
| **Prognostic clinical reasoning** | Mixed | Slow feedback (months / years); hidden by survival bias | Mixed — calibration on long horizons is poor even for skilled clinicians | Interrogate formally; require the expert to commit numbers and revisit |
| **Chess** | Kind | Fast, deterministic outcome per move | High — deliberate practice over years yields reliable intuition | Lean on intuition; surface the move tree only when the position is novel |
| **Macroeconomic forecasting** | Wicked | Decade-scale feedback; non-stationary regimes; reflexive | Low — even credentialed experts perform near chance on out-of-sample forecasts | Interrogate formally; ensemble across experts; require sensitivity bounds |
| **Supply chain operations** | Mixed | Some feedback weekly, some only after rare events | Mixed — strong on routine, weak on tail risk | Lean on intuition for routine flow; interrogate formally for tail-risk parameters |
| **Strategic management** | Wicked | Years-long feedback loops; confounded by everything | Low — overconfidence is the dominant failure mode | Interrogate formally; structured Delphi or IDEA; never accept a point estimate |"""

# === Ch 18 ===
TABLES["Three query types mapped to the Ladder"] = """| Rung | Question form | Operations example from this chapter | What the SCM does to answer it | When in the pipeline |
|---|---|---|---|---|
| **Rung 1 — Association** | $P(Y \\mid X)$ — what tends to co-occur? | "Among customers who saw the price change, what was the retention rate?" | Reads from the joint distribution implied by the parameterized SCM | Recommendation context — calibrating the baseline |
| **Rung 2 — Intervention** | $P(Y \\mid do(X))$ — what happens if we act? | "If we *set* the price 12% higher, what is the projected retention rate?" | Modifies the SCM by replacing the structural equation for $X$, propagates forward | Recommendation core — EV ranking lives here |
| **Rung 3 — Counterfactual** | $P(Y_{X'} \\mid X, Y)$ — what would have happened if we'd acted differently? | "Given that we raised the price 12% last quarter and saw the observed retention, what would retention have been at 6%?" | Abduction-action-prediction on the parameterized SCM with case-specific noise recovered | Retrospective audit — the section of the executive report that defends the recommendation |"""

TABLES["Knapsack variants"] = """| Variant | What it adds to the basic formulation | Constraint type | Operations example | When the simpler formulation fails |
|---|---|---|---|---|
| **0-1 Knapsack** | Each intervention is included or excluded — no fractional adoption | $\\sum_i x_i c_i \\leq B$, $x_i \\in \\{0, 1\\}$ | Pick which product launches to fund this quarter | When indivisibility is binding (most strategic interventions) |
| **Multidimensional** | Multiple budget dimensions — money, headcount, calendar weeks | $\\sum_i x_i c_{ij} \\leq B_j$ for each resource $j$ | A project that needs both engineering capacity and legal review time | When a single budget hides binding non-monetary constraints |
| **Logical-dependency** | Some interventions require others as prerequisites | $x_i \\leq x_j$ if $i$ depends on $j$ | "Pricing change requires a contract template update first" | When dependencies make some "EV-positive" interventions infeasible alone |
| **Multiple-choice** | Mutually exclusive groups of interventions | $\\sum_{i \\in g} x_i \\leq 1$ for each group $g$ | "Pick at most one of A/B/C pricing strategies" | When alternatives genuinely conflict — not all positives can stack |
| **Chance-constrained** | Constraints hold with probability $\\geq 1-\\alpha$ rather than deterministically | $P(\\sum_i x_i c_i \\leq B) \\geq 1 - \\alpha$ | Budget that must hold under uncertain costs at 95% confidence | When deterministic budgets ignore the uncertainty in the underlying parameters |

*Each variant addresses a class of real operational constraint; the full portfolio optimization typically needs all four combined.*"""

# === Ch 19 ===
TABLES["Three-column recommendation quality rubric"] = """| | Unspecific | Unsized | Well-formed |
|---|---|---|---|
| **Example text** | "Management should consider pricing actions." | "Raise enterprise prices by 12% in Europe." | "Raise enterprise prices by 12% in Europe before Sept 15. Owner: Head of Enterprise Pricing. Expected revenue impact: \\$12M (90% CI: \\$7M–\\$17M). Expected churn impact: +1.4 pp (90% CI: +0.8–+2.1 pp)." |
| **What the executive cannot do** | Cannot form an execution plan — no lever, no timing, no scope | Cannot evaluate whether action is worth organizational cost — magnitudes are missing | (No deficiency) — has everything needed for execution and accountability |"""

TABLES["Example evidence section"] = """| Variable | Estimated value | Confidence | Evidence source and sample | Contribution to projected effect |
|---|---|---|---|---|
| **European enterprise price elasticity** | $-0.73$ | **HIGH** | 18 months observational data, 2,400 accounts, DML estimate, CI $[-0.84, -0.62]$ | Primary driver of the revenue projection — *trust and use* |
| **Enterprise churn sensitivity to price** | $+1.8$ pp per 10% increase | **MEDIUM** | 14 months data, 870 accounts in this tier; smaller sample, wider CI $[+0.9, +2.7]$ | Principal risk factor — *probe with domain knowledge* |
| **Competitive response lag** | 8–12 weeks | **EXPERT-ANCHORED** | VP Sales, elicitation session 2024-Q2-3, no observational support yet | Timing parameter for the NA rollout — *monitor and test* |"""

TABLES["Two-column narration evaluation rubric"] = """| Must-Do (✓ if satisfied) | Must-Never (✗ if violated) |
|---|---|
| **1. Translates the model's ranking into a specific recommendation.** First paragraph names the model's top-ranked action — actor, action, magnitude, timing. | **1. Explains the model.** No methodology paragraphs in the report — methodology lives in the appendix or the model card. |
| **2. Surfaces confidence with intervals.** Every projection includes a confidence interval at a stated confidence level. | **2. Shows the full graph.** The DAG belongs in the appendix; the report shows the active causal pathway, not the full structure. |
| **3. Flags uncertainty without undermining the recommendation.** Assumptions are stated with magnitude, not generic hedges. | **3. Presents options as equal.** The top-ranked option is the headline; alternatives are contextualized with a named shortfall. |
| **4. Grounds every claim in model evidence.** Each claim is traceable to a specific package output by file path. | **4. Claims outside the model's scope.** No assertions about legal, competitive, or macro factors not in the package. |
| **5. Produces a reasoning trace.** Logs which package outputs were consulted to produce each section. | **5. Generic apologies for uncertainty.** No "the model has limitations" language — limitations are named specifically. |
| **6. Carries a consistent identity.** Voice and structure match prior reports from this Living Model. | **6. Fabricates consensus.** No "the system recommends" without naming the specific mechanism that produced the recommendation. |
|  | **7. Acts autonomously.** No action executed without sign-off by the named accountable human. |"""


# ---------------------------------------------------------------------------

def apply():
    pat = re.compile(r'<!--\s*→\s*\[TABLE:([^]]*?)(?:\]\s*-->|-->)', re.DOTALL)
    files = sorted(CH.glob('*.md'))
    total = 0
    miss = []
    for f in files:
        text = f.read_text()

        def replace(m):
            nonlocal total
            comment_text = m.group(0)
            for key, table in TABLES.items():
                if key in comment_text:
                    total += 1
                    return table
            miss.append((f.name, comment_text[:80]))
            return comment_text

        new_text = pat.sub(replace, text)
        if new_text != text:
            f.write_text(new_text)
    print(f"replaced: {total} tables")
    if miss:
        print("\nMISSED:")
        for fn, c in miss:
            print(f"  {fn}: {c}")


if __name__ == "__main__":
    apply()
